@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jan 12 19:15:06 +0200 2019
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim sim_enc_behav -key {Behavioral:sim_1:Functional:sim_enc} -tclbatch sim_enc.tcl -view C:/Users/gabri/Desktop/CN/IDEA/IDEA_VHDL/sim_dec_behav.wcfg -view C:/Users/gabri/Desktop/CN/IDEA/IDEA_VHDL/sim_enc_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
